default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: Nicolas2010
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hellorails_development
  user: postgres
  password: Nicolas2010

 
test:
  <<: *default
  database: hellorails_test
  user: postgres
  password: Nicolas2010

production:
  <<: *default
  database: hellorails_production
  username: hellorails
  password: <%= ENV["HELLORAILS_DATABASE_PASSWORD"] %>